import json

translations = {
    "awesome-shop": "Magasin AWESOME",
    "awesome-sink": "Broyeur AWESOME",
    "alien-dna-capsule": "Capsule d'ADN étranger",
    "alien-power-augmenter": "Augmenteur de puissance étranger",
    "alien-power-matrix": "Matrice de puissance étrangère",
    "alien-protein": "Protéine étrangère",
    "alien-remains": "Restes étrangers",
    "assembler": "Assembleuse",
    "automated-gate": "Portail automatisé",
    "bacon-agaric": "Agaric de bacon",
    "bauxite": "Bauxite",
    "beacon": "Balise",
    "beam-connector": "Connecteur de poutre",
    "beam-support": "Support de poutre",
    "beryl-nut": "Noisette de béryl",
    "biochemical-sculptor": "Sculpteur biochimique",
    "biomass": "Biomasse",
    "biomass-burner": "Brûleur de biomasse",
    "black-powder": "Poudre noire",
    "blade-runners": "Exosquelette",
    "blender": "Mélangeuse",
    "block-signal": "Signal de bloc",
    "blue-power-slug": "Limace de puissance bleue",
    "blueprint-designer-mk-1": "Concepteur de plans Mk.1",
    "blueprint-designer-mk-2": "Concepteur de plans Mk.2",
    "blueprint-designer-mk-3": "Concepteur de plans Mk.3",
    "catwalk-corner": "Passerelle - Angle",
    "catwalk-intersection": "Passerelle - Intersection",
    "catwalk-ramp": "Passerelle - Rampe",
    "catwalk-stairs": "Passerelle - Escalier",
    "catwalk-t-junction": "Passerelle - Jonction en T",
    "ceiling-light": "Plafonnier",
    "chainsaw": "Tronçonneuse",
    "clean-pipeline-mk-1": "Pipeline propre Mk.1",
    "clean-pipeline-mk-2": "Pipeline propre Mk.2",
    "cluster-nobelisk": "Nobelisk à fragmentation",
    "coal-powered-generator": "Générateur à charbon",
    "color-cartridge": "Cartouche de couleur",
    "compacted-coal": "Charbon compacté",
    "construction-fence": "Barrière de chantier",
    "constructor": "Constructeur",
    "converter": "Convertisseur",
    "conveyor-belt-mk-1": "Convoyeur Mk.1",
    "conveyor-belt-mk-2": "Convoyeur Mk.2",
    "conveyor-belt-mk-3": "Convoyeur Mk.3",
    "conveyor-belt-mk-4": "Convoyeur Mk.4",
    "conveyor-belt-mk-5": "Convoyeur Mk.5",
    "conveyor-belt-mk-6": "Convoyeur Mk.6",
    "conveyor-ceiling-mount": "Support de convoyeur de plafond",
    "conveyor-lift-floor-hole": "Passage de convoyeur vertical pour sol",
    "conveyor-lift-mk-1": "Convoyeur vertical Mk.1",
    "conveyor-lift-mk-2": "Convoyeur vertical Mk.2",
    "conveyor-lift-mk-3": "Convoyeur vertical Mk.3",
    "conveyor-lift-mk-4": "Convoyeur vertical Mk.4",
    "conveyor-lift-mk-5": "Convoyeur vertical Mk.5",
    "conveyor-lift-mk-6": "Convoyeur vertical Mk.6",
    "conveyor-merger": "Groupeur de convoyeurs",
    "conveyor-pole": "Poteau de convoyeur",
    "conveyor-splitter": "Répartiteur de convoyeur",
    "conveyor-wall-mount": "Support de convoyeur mural",
    "copper-powder": "Poudre de cuivre",
    "crafting-bench": "Atelier",
    "cup": "Tasse",
    "cyber-wagon": "Cyber-wagon",
    "diamonds": "Diamants",
    "dimensional-depot-uploader": "Téléchargeur de dépôt dimensionnel",
    "display-sign": "Panneau d'affichage",
    "dissolved-silica": "Silice dissoute",
    "double-beam-connector": "Connecteur de poutre double",
    "double-wall-outlet-mk-1": "Prise murale double Mk.1",
    "double-wall-outlet-mk-2": "Prise murale double Mk.2",
    "double-wall-outlet-mk-3": "Prise murale double Mk.3",
    "drone": "Drone",
    "drone-port": "Port de drones",
    "electric-locomotive": "Locomotive électrique",
    "electromagnetic-control-rod": "Tige de contrôle électromagnétique",
    "empty-canister": "Bidon vide",
    "empty-fluid-tank": "Réservoir de fluide vide",
    "empty-platform": "Quai vide",
    "empty-platform-with-catwalk": "Quai vide avec passerelle",
    "encased-plutonium-cell": "Cellule de plutonium encastrée",
    "encased-uranium-cell": "Cellule d'uranium encastrée",
    "equipment-workshop": "Atelier d'équipement",
    "explorer": "Explorateur",
    "explosive-rebar": "Barre d'armature explosive",
    "ficsit-coupon": "Coupon FICSIT",
    "ficsmas-power-light": "Lumière de Noël FICSIT",
    "fabric": "Tissu",
    "factory-cart": "Chariot de l'usine",
    "ficsonium": "Ficsonium",
    "flood-light-tower": "Pylône d'éclairage",
    "flower-petals": "Pétales de fleurs",
    "fluid-buffer": "Réservoir de fluide",
    "fluid-freight-platform": "Quai de chargement de fluides",
    "gas-filter": "Filtre à gaz",
    "gas-mask": "Masque à gaz",
    "gas-nobelisk": "Nobelisk à gaz",
    "geothermal-generator": "Générateur géothermique",
    "giant-ficsmas-tree": "Arbre de Noël géant",
    "glass-frame-foundation": "Fondation en verre à cadre",
    "golden-factory-cart": "Chariot d'usine doré",
    "hatcher-remains": "Restes de pondeur",
    "hazard-storage-box": "Coffre de stockage des matières dangereuses",
    "hazmat-suit": "Combinaison antiradiation",
    "heat-sink": "Dissipateur thermique",
    "high-barrier": "Barrière haute",
    "hog-remains": "Restes de sanglier",
    "homing-rifle-ammo": "Munition de fusil à tête chercheuse",
    "hoverpack": "Turbo-propulseur",
    "hypertube": "Hypertube",
    "hypertube-entrance": "Entrée d'hypertube",
    "hypertube-floor-hole": "Passage d'hypertube pour sol",
    "hypertube-support": "Support d'hypertube",
    "hypertube-wall-hole": "Passage d'hypertube mural",
    "hypertube-wall-support": "Support d'hypertube mural",
    "industrial-fluid-buffer": "Réservoir de fluide industriel",
    "industrial-storage-container": "Conteneur de stockage industriel",
    "iodine-infused-filter": "Filtre infusé à l'iode",
    "ionized-fuel": "Carburant ionisé",
    "iron-rebar": "Barre d'armature en fer",
    "jetpack": "Jetpack",
    "jump-pad": "Plaque de saut",
    "ladder": "Échelle",
    "large-billboard": "Grand panneau publicitaire",
    "leaves": "Feuilles",
    "light-control-panel": "Panneau de contrôle de l'éclairage",
    "liquid-biofuel": "Biocarburant liquide",
    "lookout-tower": "Tour de guet",
    "low-barrier": "Barrière basse",
    "mam": "M.A.M.",
    "main-portal": "Portail principal",
    "manufacturer": "Façonneuse",
    "medical-storage-box": "Coffre médical",
    "medicinal-inhaler": "Inhalateur médicinal",
    "mercer-sphere": "Sphère de Mercer",
    "metal-beam": "Poutre métallique",
    "miner-mk-1": "Foreuse Mk.1",
    "miner-mk-2": "Foreuse Mk.2",
    "miner-mk-3": "Foreuse Mk.3",
    "modern-railing": "Garde-corps moderne",
    "motor": "Moteur",
    "mycelia": "Mycélium",
    "neural-quantum-processor": "Processeur neuro-quantique",
    "nitric-acid": "Acide nitrique",
    "nitrogen-gas": "Azote gazeux",
    "nobelisk": "Nobelisk",
    "nobelisk-detonator": "Détonateur de Nobelisk",
    "non-fissile-uranium": "Uranium non fissile",
    "nuclear-power-plant": "Centrale nucléaire",
    "nuke-nobelisk": "Nobelisk nucléaire",
    "object-scanner": "Scanner d'objets",
    "oil-extractor": "Extracteur de pétrole",
    "packaged-alumina-solution": "Solution d'alumine emballée",
    "packaged-fuel": "Carburant emballé",
    "packaged-heavy-oil-residue": "Résidu d'huile lourde emballé",
    "packaged-ionized-fuel": "Carburant ionisé emballé",
    "packaged-liquid-biofuel": "Biocarburant liquide emballé",
    "packaged-nitric-acid": "Acide nitrique emballé",
    "packaged-nitrogen-gas": "Azote gazeux emballé",
    "packaged-oil": "Pétrole emballé",
    "packaged-rocket-fuel": "Carburant de fusée emballé",
    "packaged-sulfuric-acid": "Acide sulfurique emballé",
    "packaged-turbofuel": "Turbocarburant emballé",
    "packaged-water": "Eau emballée",
    "packager": "Emballeuse",
    "painted-beam": "Poutre peinte",
    "paleberry": "Baie pâle",
    "parachute": "Parachute",
    "particle-accelerator": "Accélérateur de particules",
    "path-signal": "Signal de chemin",
    "personal-storage-box": "Coffre de stockage personnel",
    "petroleum-coke": "Coke de pétrole",
    "pipeline-floor-hole": "Passage de pipeline pour sol",
    "pipeline-junction": "Jonction de pipeline",
    "pipeline-mk-1": "Pipeline Mk.1",
    "pipeline-mk-2": "Pipeline Mk.2",
    "pipeline-pump-mk-1": "Pompe de pipeline Mk.1",
    "pipeline-pump-mk-2": "Pompe de pipeline Mk.2",
    "pipeline-support": "Support de pipeline",
    "pipeline-wall-hole": "Passage de pipeline mural",
    "pipeline-wall-support": "Support de pipeline mural",
    "plastic": "Plastique",
    "plutonium-fuel-rod": "Barre de plutonium",
    "plutonium-pellet": "Boulette de plutonium",
    "plutonium-waste": "Déchets de plutonium",
    "polymer-resin": "Résine polymère",
    "portable-miner": "Foreuse portable",
    "portrait-sign": "Panneau portrait",
    "power-line": "Ligne électrique",
    "power-pole-mk-1": "Poteau électrique Mk.1",
    "power-pole-mk-2": "Poteau électrique Mk.2",
    "power-pole-mk-3": "Poteau électrique Mk.3",
    "power-shard": "Éclat de puissance",
    "power-shard-1": "Éclat de puissance (1)",
    "power-shard-2": "Éclat de puissance (2)",
    "power-shard-5": "Éclat de puissance (5)",
    "power-slug": "Limace de puissance",
    "power-storage": "Accumulateur électrique",
    "power-switch": "Interrupteur électrique",
    "power-tower": "Pylône électrique",
    "power-tower-platform": "Pylône électrique avec plateforme",
    "pressure-conversion-cube": "Cube de conversion de pression",
    "priority-power-switch": "Interrupteur électrique prioritaire",
    "programmable-splitter": "Répartiteur programmable",
    "pulse-nobelisk": "Nobelisk à impulsion",
    "purple-power-slug": "Limace de puissance violette",
    "quantum-encoder": "Encodeur quantique",
    "quartz-crystal": "Cristal de quartz",
    "quickwire": "Fil actif",
    "radar-tower": "Tour radar",
    "radio-control-unit": "Unité de contrôle radio",
    "railway": "Chemin de fer",
    "raw-quartz": "Quartz brut",
    "reanimated-sam": "SAM réanimé",
    "rebar-gun": "Lance-barres d'armature",
    "refinery": "Raffinerie",
    "rifle": "Fusil",
    "rifle-ammo": "Munition de fusil",
    "road-barrier": "Barrière de route",
    "rocket-fuel": "Carburant de fusée",
    "rotor": "Rotor",
    "rubber": "Caoutchouc",
    "sam": "SAM",
    "sam-fluctuator": "Fluctuateur SAM",
    "satellite-portal": "Portail satellite",
    "screw": "Vis",
    "shatter-rebar": "Barre d'armature à fragmentation",
    "silica": "Silice",
    "singularity-cell": "Cellule de singularité",
    "small-billboard": "Petit panneau publicitaire",
    "smart-plating": "Placage intelligent",
    "smart-splitter": "Répartiteur intelligent",
    "smelter": "Fonderie",
    "smokeless-powder": "Poudre sans fumée",
    "solid-biofuel": "Biocarburant solide",
    "somersloop": "Somersloop",
    "space-elevator": "Ascenseur orbital",
    "spitter-protein": "Protéine de cracheur",
    "square-sign-0-5-m": "Panneau carré (0,5 m)",
    "square-sign-1-m": "Panneau carré (1 m)",
    "square-sign-2-m": "Panneau carré (2 m)",
    "stackable-conveyor-pole": "Poteau de convoyeur empilable",
    "stackable-hypertube-support": "Support d'hypertube empilable",
    "stackable-pipeline-support": "Support de pipeline empilable",
    "stator": "Stator",
    "steel-beam": "Poutre d'acier",
    "steel-ingot": "Lingot d'acier",
    "steel-pipe": "Tuyau d'acier",
    "stinger-protein": "Protéine de rodeur",
    "storage-container": "Conteneur de stockage",
    "straight-catwalk": "Passerelle droite",
    "street-light": "Réverbère",
    "stun-rebar": "Barre d'armature étourdissante",
    "sulfur": "Soufre",
    "sulfuric-acid": "Acide sulfurique",
    "supercomputer": "Superordinateur",
    "superposition-oscillator": "Oscillateur de superposition",
    "tarp-construction-fence": "Bâche de chantier",
    "the-hub": "Le HUB",
    "therapeutic-inhaler": "Inhalateur thérapeutique",
    "thermal-propulsion-rocket": "Fusée à propulsion thermique",
    "time-crystal": "Cristal temporel",
    "tractor": "Tracteur",
    "train-station": "Gare ferroviaire",
    "truck": "Camion",
    "truck-station": "Station de camions",
    "turbo-motor": "Turbomoteur",
    "turbo-rifle-ammo": "Munition de fusil turbo",
    "turbofuel": "Turbocarburant",
    "u-jelly-landing-pad": "Plateforme d'atterrissage Jelly",
    "uranium": "Uranium",
    "uranium-fuel-rod": "Barre d'uranium",
    "uranium-waste": "Déchets d'uranium",
    "valve": "Valve",
    "versatile-framework": "Ossature polyvalente",
    "vines": "Lianes",
    "wall-outlet-mk-1": "Prise murale Mk.1",
    "wall-outlet-mk-2": "Prise murale Mk.2",
    "wall-outlet-mk-3": "Prise murale Mk.3",
    "wall-mounted-flood-light": "Pylône d'éclairage mural",
    "water-extractor": "Extracteur d'eau",
    "wire": "Fil électrique",
    "wood": "Bois",
    "xeno-basher": "Xéno-basheur",
    "xeno-zapper": "Xéno-zappeur",
    "yellow-power-slug": "Limace de puissance jaune",
    "zipline": "Tyrolienne"
}

with open('src/data/items.json', 'r') as f:
    items = json.load(f)

for item in items:
    if item['id'] in translations:
        item['name'] = translations[item['id']]

with open('src/data/items.json', 'w') as f:
    json.dump(items, f, indent=2, ensure_ascii=False)

with open('src/data/recipes.json', 'r') as f:
    recipes = json.load(f)

for recipe in recipes:
    if not recipe['isAlternate'] and len(recipe['products']) == 1:
        prod_id = recipe['products'][0]['itemId']
        if prod_id in translations:
            recipe['name'] = translations[prod_id]

    if recipe['isAlternate'] and len(recipe['products']) == 1:
         prod_id = recipe['products'][0]['itemId']
         if prod_id in translations:
             recipe['name'] = translations[prod_id] + " (Alternatif)"

with open('src/data/recipes.json', 'w') as f:
    json.dump(recipes, f, indent=2, ensure_ascii=False)

print("Applied bulk translations.")
